kind: Namespace
apiVersion: v1
metadata:
  name: external-dns
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cf-dns
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: key-cloudflare
      remoteRef:
        key: cf-dns
        property: cloudflare-argo
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.22.0
    helm:
      valuesObject:
        provider:
          name: cloudflare
        fullnameOverride: external-dns
        policy: sync
        registry: txt
        txtOwnerId: kubernetes
        sources:
          - service
          - crd
        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cf-dns
                key: key-cloudflare
        extraArgs:
          - "--annotation-filter=external-dns.custom/type in (public)"
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    # syncOptions:
    # - serversideApply=true
    # - force-conflicts=true
